version: '3.7'

services: 
  lib:
    container_name: lib
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_USER_POOL_ID=${AWS_USER_POOL_ID}
      - AWS_CLIENT_APP_ID=${AWS_CLIENT_APP_ID} 
    volumes:
      - ./:/project
    command: ["npm", "run", dev]
